## Numpy Labs


### 1. abc_numpy

In [1]:
#Create a numpy array of strings containing letters 'a' through 'j' (inclusive) of the alphabet. Then, use numpy array attributes to print the following information about this array:

#dtype of array

#shape of array
#size of array

#The code you submit in the code editor below will not be graded. Use the results from your code below, along with what you remember from the previous video, to complete the quiz below the code editor.



import numpy as np

# create numpy array of letters a-j

letter = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
letter_array = np.array(letter)
print("Letter Array: ", letter_array)

# get dtype of array

print(letter_array.dtype)


# get shape of array

print(letter_array.shape)


# get size of array

print(letter_array.size)


Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
<U1
(10,)
10


### 2. create_ndarray

In [2]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 


nums = np.arange(4)
nums_2d = nums.reshape(4)
y = np.ones((4,4))
X = nums + y
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### 3. create_ndarray1

In [3]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

even_nums = np.arange(2, 33, 2)

X = even_nums.reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


### 4. pick_odd

In [4]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).

x = np.arange(1, 26)
X = x.reshape(5, 5)
print(X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
